version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: quest_api_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - quest_api_postgres_data:/var/lib/postgresql/data

volumes:
  quest_api_postgres_data: 